### ISSUE TITLE
Discovery  problem

### ISSUE THREAD

**Issue by damienbod** [damienbod/AspNet5IdentityServerAngularImplicitFlow#54]
An unhandled exception was thrown by the application. (8c14976b)
System.InvalidOperationException: Discovery endpoint https://localhost:44318/.well-known/openid-configuration is unavailable: System.Net.Http.HttpRequestException:

**Comment by damienbod** [comment]
At Ani, Jamie
I'm trying to reproduce this and I can't. I created a new issue for this.

Could you try the following

1) Rebuild the whole solution
2) Stop all scripts running in the task runner
2) delete everything in .\src\AngularClient\node_modules
3) using the commandline at .\src\AngularClient
> npm install
> npm run build-production
4) start IdentityServerWithIdentitySQLite
5) start ResourceServer 
6) start ResourceFileServer 
7) start AngularClient

Greetings Damien

**Comment by damienbod** [comment]
From Jamie

Actually problem is that API – ResourceFileServer (44378 port) can’t hit Identity server – IdentityServerWithIdentitySQLite (44318 port )

I can access the discovery address from browser – https://localhost:44318/.well-known/openid-configuration, but it seems API can’t access it for some reason. Any ideas please?

No Errors in logs for Identity Server app.

Log from Web API:

An unhandled exception was thrown by the application. (8c14976b)
System.InvalidOperationException: Discovery endpoint https://localhost:44318/.well-known/openid-configuration is unavailable: System.Net.Http.HttpRequestException: An error occurred while sending the request. —> System.Net.Http.WinHttpException: A security error occurred
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.Http.WinHttpHandler.d__105.MoveNext()
— End of inner exception stack trace —
