### ISSUE TITLE
VS 2017 Issue

### ISSUE THREAD

**Issue by klanglie** [damienbod/AspNet5IdentityServerAngularImplicitFlow#95]
I have tried running the latest code and VS 2017 hangs. So I copied the server code and changed it to use Sql Server. I also copied the client code and bolted it to my app. I was originally going to use OpenIddict.

https://github.com/klanglie/OpenUpdate (You can take a look at these two projects: SPA + Identity). The SPA project I am running from VS Code. No SSL. Is this required or can I disable it on the serverver? I can get through the entire flow, create login, login, redirect back. http://localhost:3000/login#id_token=eyjhbgcioijsu........ 

Except now the id_token is not being retrieved and the Login link in the corner is not changing to logout.

So I guess my questions are:
Is client ssl mandatory or can I disable it? 
How do I ensure that the return id_token is consumed by the app and changing the login status and setting the session variables. I haven't stepped through the code any.

Thanks,

Kai

**Comment by klanglie** [comment]
I made some changes and noticed bad console output. I don't think I checked console before. But it is likely same bug returned from IS4 callback:

main.bundle.js:2300 ERROR SyntaxError: Unexpected token ( in JSON at position 1
    at Object.parse (<anonymous>)
    at OidcSecurityValidation.getPayloadFromToken (http://localhost:3000/main.bundle.js:81835:25)
    at SafeSubscriber._next (http://localhost:3000/main.bundle.js:74195:69)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3000/main.bundle.js:16767:16)
    at SafeSubscriber.next (http://localhost:3000/main.bundle.js:16714:22)
    at Subscriber._next (http://localhost:3000/main.bundle.js:16654:26)
    at Subscriber.next (http://localhost:3000/main.bundle.js:16618:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/main.bundle.js:16654:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/main.bundle.js:16618:18)
    at MapSubscriber._next (http://localhost:3000/main.bundle.js:65383:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/main.bundle.js:16618:18)
    at XMLHttpRequest.onLoad (http://localhost:3000/main.bundle.js:43327:38)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:13309:31)
    at Object.onInvokeTask (http://localhost:3000/main.bundle.js:5161:33)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:13308:36)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:13076:47)
    at ZoneTask.invokeTask [as invoke] (http://localhost:3000/polyfills.bundle.js:13383:34)
    at invokeTask (http://localhost:3000/polyfills.bundle.js:14424:14)
    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:3000/polyfills.bundle.js:14450:17)
    at ____________________Elapsed_55_ms__At__Thu_Oct_19_2017_17_57_37_GMT_0400__Eastern_Daylight_Time_ (http://localhost)

TOKEN:

#id_token=eyjhbgcioijsuzi1niisimtpzci6ija2rdnfndzfotewnzndnuq0qkmyqzk5odncrtlgrjq0oengnjqwrdqilcj0exaioijkv1qilcj4nxqioijcdfbrynbfsfbgmux3c21zty1ux1jjejjrtleifq.eyjuymyioje1mdg0ntayntusimv4cci6mtuwodq1mdu1nswiaxnzijoiahr0chm6ly9sb2nhbghvc3q6ndqzmtgilcjhdwqioijhbmd1bgfyy2xpzw50iiwibm9uy2uioijomc4ymtcwmtu5otizmty3mjm0mje1mdg0ntayntu3njgilcjpyxqioje1mdg0ntayntusimf0x2hhc2gioiixzeq0dernoeo1vvbfswt2cwpumutbiiwic2lkijoimwjmndaxmwq1mwnmogi3ntq4nzvkmzbjnwm4yzlknjiilcjzdwiioii2ymywmja1ns1lntgxltqyzmetyji3ny00zdzim2jmmgm4nteilcjhdxrox3rpbwuioje1mdg0ndkymtcsimlkcci6imxvy2fsiiwiyw1yijpbinb3zcjdfq.qq6isolu-x2hk-scpgejoqv5be9ehmgje5id5uogpxxfl7ybroalvby5ksgjmmkdeonbwli8wp_erxknlvfa7romz92svovvvo-oztjuq3ltkz-pgpmqu0suyruw6agyornc8clxhs0o9g7fpv4zmkl6teyg3r4vp4pmvwnf5q2qj9swmycad8v3evighvimfopjgz5p3xszyzrcof9x6pe-tswcu_188bw_wphr2fmqkjfrzv_tre7n7nzcyblnrnkanlzupl-nqwscffdgvo6yvymog4wsxrl2spxnqhrlrxmm51qjipbihwiu4iegxtor33b6hmmfdjndw9d-9w&access_token=a7be6db3932cc9452c1603a84202ffa2cd30a65469d42ab03cca01bdfeeb5e88&token_type=bearer&expires_in=330&scope=openid%20profile%20dataeventrecords%20securedfiles&state=15084502497270.033773904605738814&session_state=ruqgcgh_gomtm_cee9xht_dgo5el88-ru7jtfsx5s3s.9a5c2f2eaccb294a0584322010489034

**Comment by klanglie** [comment]
Got past this...
